### ISSUE TITLE
Why is there so much stuff in rmgpy.data.kinetics.__init__.py?

### ISSUE THREAD

**Issue by nickvandewiele** [GreenGroup/RMG-Py#344]
Unlike the `__init__.py` modules of the other packages in RMG-Py, the one of `rmgpy.data.kinetics` is filled with a lot of code: 1 pretty giant class `KineticsDatabase` and one method `filterReactions(...)`.

For reasons of consistency and transparancy, I would advocate to move that code to another module, e.g. `common`.

Or is there a reason not to?

**Comment by rwest** [comment]
I see your motivation.
But how would imports work? I guess it could be reasonably clean.
I assume a bunch of other classes inherit from the `KineticsDatabase` class.

**Comment by jwallen** [comment]
I believe this is because `rmgpy.data.kinetics` started as a single module, before becoming so large that it was converted into a subpackage. My intention was that people would generally still interact with it as if it was a single module, i.e. always import things from `rmgpy.data.kinetics` and not worry about the subpackage layout.

Also, `KineticsDatabase` is not a base class, but is instead a high-level class that helps encapsulate a lot of the functionality in the package. (Or at least that was the idea.) Therefore, if you want to move it out of the `__init__.py`, I'd put it in a submodule named something like `main` rather than `common`. Of course, `main` might not be the best name due to the special meaning given to `__main__.py` files.

As far as I can tell, the only guidance in the Python docs is that `__init__.py` can be empty or can contain initialization code for the module (as implied by the name). You're right that what's currently in there doesn't really qualify. Probably best practice is to keep the `__init__.py` contents to a minimum, e.g. for short convenience functions and aliases.

No matter what, I would not recommend putting base classes in an `__init__.py` of a package containing submodules that construct derived classes, as the imports would be really confusing. That's what I'd use a `common` or `base` submodule for.

**Comment by nickvandewiele** [comment]
@jwallen : thanks for the historic perspective.

bf24af8ab81828ae0b3a7e4446405cc59d88eb50 attempts to move `KineticsDatabase` to a new module *database* and takes care of the changes in imports throughout RMG-Py. The module name was chosen over *base*, *common* or *main* for the reasons cited here above.

successfully tested on `examples/rmg/minimal`.
